import { Julius_Sans_One } from "next/font/google";
import "./globals.css";

const julius_Sans_One = Julius_Sans_One({ subsets: ["latin"], display: "swap", weight: '400'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={julius_Sans_One.className}>{children}</body>
    </html>
  );
}
